vim.lsp.set_log_level("error")

require("bootstrap")
require("options")
require("plugins")
require("colors")
require("keymaps")
require("autocmds")
require("lsp")
require("mycmp")
require("treesitter")
require("custom.java_scratch")
